# Generated by Django 5.1.4 on 2025-01-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
